{
 "title": "Monitoreo Lambda",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Invocaciones Lambda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/Lambda",
     "metricName": "Invocations",
     "statistics": [ "Sum" ],
     "dimensions": { "FunctionName": "enviarNotificacion" },
     "period": 300
    }
   ]
  },
  {
   "title": "Errores Lambda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/Lambda",
     "metricName": "Errors",
     "statistics": [ "Sum" ],
     "dimensions": { "FunctionName": "enviarNotificacion" },
     "period": 300
    }
   ]
  },
  {
   "title": "Duración Promedio Lambda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "region": "us-east-1",
     "namespace": "AWS/Lambda",
     "metricName": "Duration",
     "statistics": [ "Average" ],
     "dimensions": { "FunctionName": "enviarNotificacion" },
     "period": 300
    }
   ]
  }
 ]
}