version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-encuesta
    user: root
    ports:
      - "8080:8080"  
      - "50000:50000" 
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/app   
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      - app-network

  docker-agent:  
    image: docker:24.0.7-dind
    container_name: docker-agent
    privileged: true
    ports:
      - 2375:2375  
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"  
    container_name: docker-grafana-1
    volumes:
      - ./monitoring/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana-dashboard.json:/etc/grafana/provisioning/dashboards/grafana-dashboard.json
    networks:
      - app-network

volumes: 
  jenkins_home:

networks:
   app-network: