pipeline {
    agent any

    stages {
        stage('Clonar') {
            steps {
                echo 'Clonando repositorio...'
                checkout scm
            }
        }

        stage('Instalación') {
            steps {
                sh 'npm install'  // Ejecuta npm install para instalar dependencias de Node.js
            }
        }

        stage('Pruebas') {
            steps {
                sh 'npm test'  // Ejecuta las pruebas definidas en el proyecto
            }
        }
    }
}