pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1' 
        TF_IN_AUTOMATION = 'true'
    }

    stages {
        stage('Clonar Repositorio') {
            steps {
                git 'https://github.com/AChafloqueR/Encuesta-Inteligente.git'
            }
        }

        stage('Instalar Dependencias') {
            steps {
                sh 'npm install'
            }
        }

        stage('Pruebas Unitarias') {
            steps {
                sh 'npm test'
            }
        }

        stage('Análisis de Seguridad (Checkov)') {
            steps {
                sh 'checkov -d terraform/'
            }
        }

        stage('Despliegue Terraform') {
            steps {
                dir('terraform') {
                    sh 'terraform init'
                    sh 'terraform plan'
                    sh 'terraform apply -auto-approve'
                }
            }
        }

        stage('Desplegar Frontend (S3)') {
            steps {
                dir('frontend') {
                    sh '''
                    aws s3 sync . s3://tu-bucket --delete
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Todo se desplegó correctamente'
        }
        failure {
            echo 'Falló algo en el pipeline'
        }
    }
}