name: Deploy Infraestructura en AWS con Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Plan y Apply Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar configuración
        run: terraform validate

      - name: Planificar cambios
        run: terraform plan

      - name: Aplicar cambios
        run: terraform apply -auto-approve

  checkov:
    name: Análisis de seguridad con Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Checkov
        run: pip install checkov

      - name: Ejecutar Checkov
        run: checkov -d ./terraform --compact --framework terraform