name: Despliegue Automático - Encuesta Inteligente
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: "Aplicar infraestructura y frontend"
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias frontend
        working-directory: ./frontend
        run: |
          npm install

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validar Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Aplicar Terraform (modo automático)
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Finalizado
        run: echo "Despliegue completado correctamente"